# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSmartLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcuts', models.TextField(help_text=b'Please enter one shortcut for the smartlink per line.\nEach [[ shortcut ]] will resolve to the specified URL.', max_length=300, verbose_name=b'Shortcuts for the smartlink')),
                ('url', models.CharField(help_text=b'The URL smartlink will resolve to.', max_length=300, verbose_name=b'Absolute or relative URL')),
                ('description', models.TextField(blank=True, help_text=b'Optional description for the smartlink.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=300)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='indexentry',
            unique_together=set([('value', 'content_type', 'object_id')]),
        ),
    ]
